---


ovpn_key_country:  "UA"
ovpn_key_province: "Kiev"
ovpn_key_city: "Kiev"
ovpn_key_org: "workcentre"
ovpn_key_ou: "IT Department"
ovpn_days_valid: "2000"
openssl_request_subject: "/C={{ ovpn_key_country }}/ST={{ ovpn_key_province }}/L={{ ovpn_key_city }}/O={{ ovpn_key_org }}/OU={{ ovpn_key_ou }}"
ovpn_key_size: "2048"
ovpn_cipher: "BF-CBC"
ovpn_auth_digest: "SHA1"
ovpn_path: "./ovpn"
ovpn_ca: "{{ ovpn_path }}/ca"
ovpn_dhparam: "{{ ovpn_path }}/dh{{ ovpn_key_size }}.pem"
ovpn_hmac_firewall: "{{ ovpn_path }}/ta.key"
ovpn_server: "tendo.local"
ovpn_port: "1194"
ovpn_protocol: "udp"

