---
- name: Generate the RSA keys
  command: openssl genrsa -out {{ item }}.key {{ ovpn_key_size }}
  args:
    chdir: "{{ ovpn_path }}"
    creates: "{{ item }}.key"
  with_items:
    - ca
    - server

- name: Create directories for clients
  file:
    path: "{{ ovpn_path}}/{{ item }}"
    state: directory
  with_items: "{{ ovpn_clients }}"

- name: Generate RSA keys for the Clients
  command: openssl genrsa -out {{ item }}.key {{ ovpn_key_size }}
  args:
    chdir: "{{ ovpn_path }}/{{ item }}"
    creates: "{{ item }}.key"
  with_items: "{{ ovpn_clients }}"

- name: Set the proper permissions on all RSA keys
  file:
    path: "{{ ovpn_path }}"
    owner: root
    group: root
    mode: 0600
    state: directory
    recurse: yes
 
- name: Generate CA certificate
  command: openssl req -nodes -batch -new -x509 -key {{ ovpn_ca }}.key -out {{ ovpn_ca }}.crt
            -days {{ ovpn_days_valid }} -subj "{{ openssl_request_subject }}/CN=ca-certificate"
  args:
    creates: "{{ ovpn_ca }}.crt"


- name: Generate the CSR for the Server
  command: openssl req -batch -extensions server -new -key server.key -out server.csr -config {{ ovpn_path }}/openssl-server-certificate.cnf
  args:
    chdir: "{{ ovpn_path }}"
    creates: server.csr

- name: Generate the Certificate for the Server
  command: openssl ca -batch -extensions server -in server.csr -out server.crt -config openssl-server-certificate.cnf
  args:
    chdir: "{{ ovpn_path }}"
    creates: server.crt

- name: Generate CSRs for the clients
  command: openssl req -new -key {{ item }}.key -out {{ item }}.csr -subj "{{ openssl_request_subject }}/CN={{ item }}"
  args:
    chdir: "{{ ovpn_path }}/{{ item }}"
    creates: "{{ item }}.csr"
  with_items: "{{ ovpn_clients }}"

- name: Generate certificates for the clients
  command: openssl x509 -CA {{ ovpn_ca }}.crt -CAkey {{ ovpn_ca }}.key -CAcreateserial -req -days {{ ovpn_days_valid }} -in {{ item }}.csr -out {{ item }}.crt
  args:
    creates: "{{ item }}.crt"
    chdir: "{{ ovpn_path }}/{{ item }}"
  with_items: "{{ ovpn_clients }}"
           
- name: Generate the HMAC firewall key
  command: ovpn --genkey --secret {{ ovpn_hmac_firewall }}
  args:
    creates: "{{ ovpn_hmac_firewall }}"


- name: Register client certificate contents
  command: cat {{ item }}.crt
  args:
    chdir: "{{ ovpn_path }}/{{ item }}"
  with_items: "{{ ovpn_clients }}"
  register: ovpn_client_certificates

- name: Register client key contents
  command: cat {{ item }}.key
  args:
    chdir: "{{ ovpn_path }}/{{ item }}"
  with_items: "{{ ovpn_clients }}"
  register: ovpn_client_keys

- name: Create the client configs
  template:
    src: client.cnf.j2
    dest: "{{ ovpn_path }}/{{ item[0] }}/{{ ovpn_server }}.ovpn"
  no_log: yes
  with_together:
    - "{{ ovpn_clients }}"
    - "{{ ovpn_client_certificates.results }}"
    - "{{ ovpn_client_keys.results }}"

- name: Generate Diffie-Hellman parameters (this will take a while)
  command: openssl dhparam -out {{ ovpn_dhparam }} {{ ovpn_key_size }} -dsaparam
  args:
    creates: "{{ ovpn_dhparam }}"

